// food-manager — PicoMate backend server (Axum + SQLite + Ollama)
//
// Architecture:
//   Pico W / Adafruit Memento  ──HTTP GET──▶  food-manager (this server)
//                                                  │
//                                         SQLite: food.db
//                                                  │
//                                         Ollama :11434 (nemotron-3-nano)
//
// Packed endpoints (text/plain, device-friendly):
//   GET /api/menu/packed    — all foods by category; device picks one per category by date seed
//   GET /api/browse/packed  — ingredient index + per-ingredient food lists for browse UI
//   GET /api/recipe/prefetch?food=<name>  — kicks off background LLM generation, returns fast
//   GET /api/recipe/packed?food=<name>    — returns recipe or "GENERATING" if still in-flight
//
// Recipe caching strategy:
//   Recipes are stored permanently keyed by food name (UNIQUE(food)).
//   Once generated for any food, subsequent requests return from SQLite instantly — no LLM call.
//   On startup, all uncached foods are pre-generated sequentially in a background task so the
//   device never waits for Ollama during normal use.
//
// JSON endpoints (web UI):
//   CRUD for /api/foods/:category, /api/condiments, /api/ingredients
//   POST /api/recipe/generate?food=<name>  — force-regenerate a cached recipe
//
// Running:
//   ./flash.sh server-build   — release build + launchd restart
//   ./flash.sh logs           — tail server log

use axum::{
    extract::{Extension, Path, Query, State},
    http::{header, StatusCode},
    response::IntoResponse,
    routing::{delete, get, post, put},
    Json, Router,
};
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, Mutex};
use tower_http::services::ServeDir;

type Db         = Arc<Mutex<Connection>>;
type InProgress = Arc<Mutex<HashSet<String>>>;  // food names currently being generated by Ollama

#[derive(Debug, Serialize, Deserialize)]
struct FoodItem {
    #[serde(default)]
    id:         i64,
    name:       String,
    #[serde(default)]
    notes:      String,
    #[serde(default)]
    ingredient: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct Condiment {
    #[serde(default)]
    id:   i64,
    name: String,
}

#[derive(Debug, Deserialize)]
struct FoodInput {
    name:  String,
    #[serde(default)]
    notes: String,
    #[serde(default)]
    ingredient: String,
}

// ─── Ollama API response types ─────────────────────────────────────────────────

#[derive(serde::Deserialize)]
struct OllamaResp { choices: Vec<OllamaChoice> }
#[derive(serde::Deserialize)]
struct OllamaChoice { message: OllamaMsg }
#[derive(serde::Deserialize)]
struct OllamaMsg { content: String }

fn valid_category(cat: &str) -> bool {
    matches!(cat, "breakfast" | "curries" | "snacks" | "desserts")
}

// GET /api/foods/:category
async fn list_foods(Path(cat): Path<String>, State(db): State<Db>) -> impl IntoResponse {
    if !valid_category(&cat) {
        return (StatusCode::BAD_REQUEST, Json(serde_json::json!({"error": "invalid category"}))).into_response();
    }
    let conn = db.lock().unwrap();
    let sql = format!("SELECT id, name, notes, ingredient FROM {} ORDER BY id", cat);
    let mut stmt = conn.prepare(&sql).unwrap();
    let items: Vec<FoodItem> = stmt
        .query_map([], |row| {
            Ok(FoodItem {
                id:         row.get(0)?,
                name:       row.get(1)?,
                notes:      row.get::<_, Option<String>>(2)?.unwrap_or_default(),
                ingredient: row.get::<_, Option<String>>(3)?.unwrap_or_default(),
            })
        })
        .unwrap()
        .filter_map(|r| r.ok())
        .collect();
    Json(items).into_response()
}

// POST /api/foods/:category
async fn add_food(
    Path(cat): Path<String>,
    State(db): State<Db>,
    Json(body): Json<FoodInput>,
) -> impl IntoResponse {
    if !valid_category(&cat) {
        return (StatusCode::BAD_REQUEST, Json(serde_json::json!({"error": "invalid category"}))).into_response();
    }
    if body.name.is_empty() || body.name.len() > 18 {
        return (StatusCode::BAD_REQUEST, Json(serde_json::json!({"error": "name must be 1-18 chars"}))).into_response();
    }
    let conn = db.lock().unwrap();
    let sql = format!("INSERT INTO {} (name, notes, ingredient) VALUES (?1,?2,?3)", cat);
    conn.execute(&sql, params![body.name, body.notes, body.ingredient]).unwrap();
    let id = conn.last_insert_rowid();
    Json(serde_json::json!({"id": id})).into_response()
}

// PUT /api/foods/:category/:id
async fn update_food(
    Path((cat, id)): Path<(String, i64)>,
    State(db): State<Db>,
    Json(body): Json<FoodInput>,
) -> impl IntoResponse {
    if !valid_category(&cat) {
        return (StatusCode::BAD_REQUEST, Json(serde_json::json!({"error": "invalid category"}))).into_response();
    }
    if body.name.is_empty() || body.name.len() > 18 {
        return (StatusCode::BAD_REQUEST, Json(serde_json::json!({"error": "name must be 1-18 chars"}))).into_response();
    }
    let conn = db.lock().unwrap();
    let sql = format!("UPDATE {} SET name=?1, notes=?2, ingredient=?3 WHERE id=?4", cat);
    conn.execute(&sql, params![body.name, body.notes, body.ingredient, id]).unwrap();
    Json(serde_json::json!({"ok": true})).into_response()
}

// DELETE /api/foods/:category/:id
async fn delete_food(
    Path((cat, id)): Path<(String, i64)>,
    State(db): State<Db>,
) -> impl IntoResponse {
    if !valid_category(&cat) {
        return (StatusCode::BAD_REQUEST, Json(serde_json::json!({"error": "invalid category"}))).into_response();
    }
    let conn = db.lock().unwrap();
    let sql = format!("DELETE FROM {} WHERE id=?1", cat);
    conn.execute(&sql, params![id]).unwrap();
    Json(serde_json::json!({"ok": true})).into_response()
}

// GET /api/ingredients
async fn list_ingredients(State(db): State<Db>) -> impl IntoResponse {
    let conn = db.lock().unwrap();
    let mut stmt = conn.prepare("SELECT id, name FROM ingredients ORDER BY name").unwrap();
    let items: Vec<serde_json::Value> = stmt
        .query_map([], |row| Ok((row.get::<_, i64>(0)?, row.get::<_, String>(1)?)))
        .unwrap()
        .filter_map(|r| r.ok())
        .map(|(id, name)| serde_json::json!({"id": id, "name": name}))
        .collect();
    Json(items).into_response()
}

// POST /api/ingredients
async fn add_ingredient(State(db): State<Db>, Json(body): Json<serde_json::Value>) -> impl IntoResponse {
    let name = body["name"].as_str().unwrap_or("").trim().to_string();
    if name.is_empty() {
        return (StatusCode::BAD_REQUEST, Json(serde_json::json!({"error": "name required"}))).into_response();
    }
    let conn = db.lock().unwrap();
    match conn.execute("INSERT INTO ingredients (name) VALUES (?1)", params![name]) {
        Ok(_) => Json(serde_json::json!({"id": conn.last_insert_rowid()})).into_response(),
        Err(_) => (StatusCode::CONFLICT, Json(serde_json::json!({"error": "already exists"}))).into_response(),
    }
}

// DELETE /api/ingredients/:id
async fn delete_ingredient(Path(id): Path<i64>, State(db): State<Db>) -> impl IntoResponse {
    let conn = db.lock().unwrap();
    conn.execute("DELETE FROM ingredients WHERE id=?1", params![id]).unwrap();
    Json(serde_json::json!({"ok": true})).into_response()
}

// GET /api/condiments
async fn list_condiments(State(db): State<Db>) -> impl IntoResponse {
    let conn = db.lock().unwrap();
    let mut stmt = conn.prepare("SELECT id, name FROM condiments ORDER BY id").unwrap();
    let items: Vec<Condiment> = stmt
        .query_map([], |row| Ok(Condiment { id: row.get(0)?, name: row.get(1)? }))
        .unwrap()
        .filter_map(|r| r.ok())
        .collect();
    Json(items).into_response()
}

// POST /api/condiments
async fn add_condiment(State(db): State<Db>, Json(body): Json<serde_json::Value>) -> impl IntoResponse {
    let name = body["name"].as_str().unwrap_or("").to_string();
    let conn = db.lock().unwrap();
    conn.execute("INSERT INTO condiments (name) VALUES (?1)", params![name]).unwrap();
    let id = conn.last_insert_rowid();
    Json(serde_json::json!({"id": id})).into_response()
}

// DELETE /api/condiments/:id
async fn delete_condiment(Path(id): Path<i64>, State(db): State<Db>) -> impl IntoResponse {
    let conn = db.lock().unwrap();
    conn.execute("DELETE FROM condiments WHERE id=?1", params![id]).unwrap();
    Json(serde_json::json!({"ok": true})).into_response()
}

// GET /api/menu/packed — returns all foods in all categories for device consumption.
// The device picks one item per category using a date-seeded index; it does not get
// a pre-selected menu. Format: CATEGORY\nitem\nitem\n|\n ... ---END---
async fn menu_packed(State(db): State<Db>) -> impl IntoResponse {
    println!("[→] GET /api/menu/packed");
    let conn = db.lock().unwrap();
    let categories = ["BREAKFAST", "CURRIES", "SNACKS", "DESSERTS"];
    let tables     = ["breakfast", "curries", "snacks", "desserts"];
    let mut out = String::new();
    for (cat, tbl) in categories.iter().zip(tables.iter()) {
        out.push_str(cat);
        out.push('\n');
        let sql = format!("SELECT name FROM {} ORDER BY id", tbl);
        if let Ok(mut stmt) = conn.prepare(&sql) {
            let names: Vec<String> = stmt
                .query_map([], |row| row.get(0))
                .unwrap()
                .filter_map(|r| r.ok())
                .collect();
            for name in names {
                out.push_str(&name);
                out.push('\n');
            }
        }
        out.push_str("|\n");
    }
    out.push_str("---END---\n");
    println!("[←] {} bytes", out.len());
    (StatusCode::OK, [(header::CONTENT_TYPE, "text/plain")], out)
}

// GET /api/browse/packed — ingredient browser data for device UI.
// Response has two sections:
//   1. Header block: INGREDIENTS\n<name>\n...\n|\n  (index of all ingredient names)
//   2. One block per ingredient:
//        <ingredient>\nBREAKFAST\n<food>\n...\n|\nCURRIES\n...\n|\nSNACKS\n...\n|\nDESSERTS\n...\n|\n~\n
// Terminated by ---END---
// Device caches the full response in RAM and parses sections on demand.
async fn browse_packed(State(db): State<Db>) -> impl IntoResponse {
    println!("[→] GET /api/browse/packed");
    let conn = db.lock().unwrap();
    let tables = ["breakfast", "curries", "snacks", "desserts"];

    // Collect distinct ingredients (non-null, non-empty) across all tables
    let mut ingredients: Vec<String> = Vec::new();
    for tbl in &tables {
        let sql = format!(
            "SELECT DISTINCT ingredient FROM {} WHERE ingredient IS NOT NULL AND ingredient != '' ORDER BY ingredient",
            tbl
        );
        if let Ok(mut stmt) = conn.prepare(&sql) {
            let names: Vec<String> = stmt
                .query_map([], |row| row.get(0))
                .unwrap()
                .filter_map(|r| r.ok())
                .collect();
            for name in names {
                if !ingredients.contains(&name) {
                    ingredients.push(name);
                }
            }
        }
    }
    ingredients.sort();

    let mut out = String::new();

    // Header block: list of all ingredient names
    out.push_str("INGREDIENTS\n");
    for ing in &ingredients {
        out.push_str(ing);
        out.push('\n');
    }
    out.push_str("|\n");

    // One block per ingredient
    let cat_labels = ["BREAKFAST", "CURRIES", "SNACKS", "DESSERTS"];
    for ing in &ingredients {
        out.push_str(ing);
        out.push('\n');
        for (tbl, label) in tables.iter().zip(cat_labels.iter()) {
            out.push_str(label);
            out.push('\n');
            let sql = format!(
                "SELECT name FROM {} WHERE ingredient=?1 ORDER BY id",
                tbl
            );
            if let Ok(mut stmt) = conn.prepare(&sql) {
                let names: Vec<String> = stmt
                    .query_map(params![ing], |row| row.get(0))
                    .unwrap()
                    .filter_map(|r| r.ok())
                    .collect();
                for name in names {
                    out.push_str(&name);
                    out.push('\n');
                }
            }
            out.push_str("|\n");
        }
        out.push_str("~\n");
    }
    out.push_str("---END---\n");
    println!("[←] browse {} bytes", out.len());
    (StatusCode::OK, [(header::CONTENT_TYPE, "text/plain")], out)
}

// ─── Recipe helpers ────────────────────────────────────────────────────────────
//
// Recipe flow (fire-and-forget + poll):
//   1. Device calls /api/recipe/prefetch?food=X — server spawns tokio::spawn (survives
//      client disconnect), returns {"status":"started"} immediately within the device's
//      4s HTTP timeout.
//   2. Device polls /api/recipe/packed?food=X every 5s.
//      - Returns "GENERATING\n---END---\n" while Ollama is running.
//      - Returns full packed recipe once cached.
//   3. generate_and_store() calls Ollama, parses the response, stores in SQLite with
//      INSERT OR IGNORE — if another request raced in first, the existing recipe wins.
//   4. InProgress HashSet prevents duplicate Ollama calls for the same food.
//
// All recipe lines are pre-wrapped to ≤20 chars here so devices with a 20-char display
// width (SSD1306 128×64 with 6×8 font) can render them directly.

// Days since Unix epoch — used only to pick today's default food
fn today_key() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs();
    (secs / 86400) as i64
}

// Word-wrap text so each line is ≤ max_len chars
fn word_wrap(text: &str, max_len: usize) -> Vec<String> {
    let mut result = Vec::new();
    let mut cur = String::new();
    for word in text.split_whitespace() {
        let word: String = word.chars().take(max_len).collect();
        if cur.is_empty() {
            cur = word;
        } else if cur.len() + 1 + word.len() <= max_len {
            cur.push(' ');
            cur.push_str(&word);
        } else {
            result.push(cur);
            cur = word;
        }
    }
    if !cur.is_empty() { result.push(cur); }
    result
}

// Parse the raw LLM text into (title, ingredient_lines, step_lines), each ≤20 chars.
// Handles TITLE:/INGREDIENTS:/STEPS: headers and strips bullet/number prefixes.
// Fallback: if LLM ignores the format entirely, splits text in half as ingr/steps.
fn parse_recipe_from_llm(food: &str, text: &str) -> (String, Vec<String>, Vec<String>) {
    let mut title: String = food.chars().take(20).collect();
    let mut ingr: Vec<String> = Vec::new();
    let mut steps: Vec<String> = Vec::new();
    let mut section = "";

    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() { continue; }
        let upper = line.to_uppercase();

        if upper.starts_with("TITLE:") {
            let t = line[6..].trim().to_string();
            if !t.is_empty() { title = t.chars().take(20).collect(); }
            continue;
        }
        if upper.starts_with("INGREDIENT") { section = "i"; continue; }
        if upper.starts_with("STEP") || upper.starts_with("DIRECTION")
            || upper.starts_with("INSTRUCTION") || upper.starts_with("METHOD") {
            section = "s"; continue;
        }

        // Strip leading bullets / numbers
        let clean = line.trim_start_matches(|c: char| "-*•".contains(c) || c.is_ascii_digit() || c == '.' || c == ')').trim();
        if clean.is_empty() { continue; }

        match section {
            "i" => { for w in word_wrap(clean, 20) { if ingr.len()  < 20 { ingr.push(w);  } } }
            "s" => { for w in word_wrap(clean, 20) { if steps.len() < 20 { steps.push(w); } } }
            _ => {}
        }
    }

    // Fallback: LLM ignored the format — split text in half
    if ingr.is_empty() && steps.is_empty() {
        let lines: Vec<&str> = text.lines().map(|l| l.trim()).filter(|l| !l.is_empty()).collect();
        let mid = (lines.len() / 2).min(10);
        for l in &lines[..mid]    { for w in word_wrap(l, 20) { if ingr.len()  < 20 { ingr.push(w);  } } }
        for l in &lines[mid..]    { for w in word_wrap(l, 20) { if steps.len() < 20 { steps.push(w); } } }
    }

    if ingr.is_empty()  { ingr.push("(none)".into()); }
    if steps.is_empty() { steps.push("(none)".into()); }

    (title, ingr, steps)
}

// Build the packed body stored in DB and served to device.
// Format: INGREDIENTS\n<line>\n...\n|\nSTEPS\n<line>\n...\n|\n
// Caller wraps with RECIPE\n<title>\n|\n...<body>---END---\n before sending.
fn build_recipe_packed(title: &str, ingr: &[String], steps: &[String]) -> (String, String) {
    let mut body = String::from("INGREDIENTS\n");
    for i in ingr  { body.push_str(i); body.push('\n'); }
    body.push_str("|\nSTEPS\n");
    for s in steps { body.push_str(s); body.push('\n'); }
    body.push_str("|\n");
    (title.to_string(), body)
}

// Call Ollama and return the raw LLM text
async fn call_ollama(food: &str) -> Result<String, String> {
    let ollama_url = std::env::var("OLLAMA_URL")
        .unwrap_or_else(|_| "http://100.114.105.110:11434".to_string());
    let client = reqwest::Client::new();
    let prompt = format!(
        "Write a short South Indian recipe for {}.\n\
         Use EXACTLY this format:\n\
         TITLE: <title under 20 chars>\n\
         INGREDIENTS:\n\
         - <ingredient+quantity, under 20 chars per line>\n\
         STEPS:\n\
         1. <step, under 20 chars per line>\n\
         Max 8 ingredients, 8 steps. Reply with ONLY the recipe, no extra text.",
        food
    );
    let payload = serde_json::json!({
        "model": "nemotron-3-nano:latest",
        "messages": [{"role": "user", "content": prompt}],
        "stream": false
    });
    let resp = client
        .post(format!("{}/v1/chat/completions", ollama_url))
        .json(&payload)
        .timeout(std::time::Duration::from_secs(120))
        .send()
        .await
        .map_err(|e| format!("Ollama connect failed: {e}"))?;
    let data: OllamaResp = resp.json().await
        .map_err(|e| format!("Ollama response parse failed: {e}"))?;
    data.choices.into_iter().next()
        .map(|c| c.message.content)
        .ok_or_else(|| "Empty Ollama response".into())
}

// Pick today's food item from DB (deterministic per day)
fn todays_food(conn: &Connection, key: i64) -> String {
    let sql = "SELECT name FROM curries ORDER BY id";
    conn.prepare(sql).ok()
        .and_then(|mut s| {
            s.query_map([], |r| r.get::<_, String>(0)).ok()
             .map(|it| it.filter_map(|r| r.ok()).collect::<Vec<_>>())
        })
        .filter(|v| !v.is_empty())
        .map(|v| v[(key as usize / 4) % v.len()].clone())
        .unwrap_or_else(|| "Idli".to_string())
}

// Generate recipe via Ollama and cache in DB; returns (title, body)
async fn generate_and_store(db: &Db, food: &str) -> Result<(String, String), String> {
    println!("[…] generating recipe for '{}'", food);
    let llm_text = call_ollama(food).await?;
    let (title, ingr, steps) = parse_recipe_from_llm(food, &llm_text);
    let (title, body) = build_recipe_packed(&title, &ingr, &steps);
    {
        let conn = db.lock().unwrap();
        let _ = conn.execute(
            "INSERT OR IGNORE INTO recipes (food, title, body) VALUES (?1, ?2, ?3)",
            params![food, &title, &body],
        );
    }
    Ok((title, body))
}

// GET /api/recipe/prefetch?food=<name>
// Kicks off background recipe generation and returns immediately (within device HTTP timeout).
// Returns {"status":"ready"} if already cached, {"status":"generating"} if in-flight,
// {"status":"started"} if just spawned. The tokio::spawn survives client disconnect so
// Ollama is never cancelled by a retry.
async fn recipe_prefetch(
    State(db): State<Db>,
    Extension(in_progress): Extension<InProgress>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let food = resolve_food(&db, &params, today_key());
    println!("[→] GET /api/recipe/prefetch food='{}'", food);

    // Already cached?
    {
        let conn = db.lock().unwrap();
        if conn.query_row("SELECT id FROM recipes WHERE food=?1",
            params![&food], |_| Ok(())).is_ok() {
            return Json(serde_json::json!({"status": "ready"})).into_response();
        }
    }
    // Already generating?
    if in_progress.lock().unwrap().contains(&food) {
        return Json(serde_json::json!({"status": "generating"})).into_response();
    }

    // Spawn background generation
    in_progress.lock().unwrap().insert(food.clone());
    let (db_bg, ip_bg, food_bg) = (db.clone(), in_progress.clone(), food.clone());
    tokio::spawn(async move {
        match generate_and_store(&db_bg, &food_bg).await {
            Ok((title, _)) => println!("[✓] bg recipe ready: {}", title),
            Err(e)         => eprintln!("[!] bg recipe failed: {}", e),
        }
        ip_bg.lock().unwrap().remove(&food_bg);
    });

    Json(serde_json::json!({"status": "started"})).into_response()
}

// Helper: resolve food from query param or fall back to today's curry
fn resolve_food(db: &Db, params: &HashMap<String, String>, key: i64) -> String {
    let f = params.get("food").map(|s| s.trim().to_string()).unwrap_or_default();
    if f.is_empty() { let conn = db.lock().unwrap(); todays_food(&conn, key) } else { f }
}

// GET /api/recipe/packed?food=<name>
// Returns the cached recipe if ready, "GENERATING\n---END---\n" if still in-flight, or
// generates inline if neither (direct curl fallback — not the normal device path).
// Recipes are cached permanently by food name; once generated, always instant.
async fn recipe_packed(
    State(db): State<Db>,
    Extension(in_progress): Extension<InProgress>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let food = resolve_food(&db, &params, today_key());
    println!("[→] GET /api/recipe/packed food='{}'", food);

    // Check persistent cache (any day)
    let cached = {
        let conn = db.lock().unwrap();
        conn.query_row(
            "SELECT title, body FROM recipes WHERE food=?1",
            params![&food],
            |r| Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?)),
        ).ok()
    };

    if let Some((title, body)) = cached {
        println!("[←] recipe from cache");
        let out = format!("RECIPE\n{}\n|\n{}---END---\n", title, body);
        return (StatusCode::OK, [(header::CONTENT_TYPE, "text/plain")], out).into_response();
    }

    // Still generating in background?
    if in_progress.lock().unwrap().contains(&food) {
        println!("[←] recipe still generating");
        return (StatusCode::OK, [(header::CONTENT_TYPE, "text/plain")],
                "GENERATING\n---END---\n".to_string()).into_response();
    }

    // Not cached, not generating — generate inline (fallback for direct curl calls)
    match generate_and_store(&db, &food).await {
        Ok((title, body)) => {
            let out = format!("RECIPE\n{}\n|\n{}---END---\n", title, body);
            println!("[←] recipe generated inline {} bytes", out.len());
            (StatusCode::OK, [(header::CONTENT_TYPE, "text/plain")], out).into_response()
        }
        Err(e) => {
            eprintln!("[!] recipe gen failed: {}", e);
            let out = "RECIPE\nFailed\n|\nINGREDIENTS\nOllama error\n|\nSTEPS\nCheck server\n|\n---END---\n".to_string();
            (StatusCode::OK, [(header::CONTENT_TYPE, "text/plain")], out).into_response()
        }
    }
}

// POST /api/recipe/generate?food=<name> — force-regenerate recipe for a food
async fn recipe_generate(
    State(db): State<Db>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let food = resolve_food(&db, &params, today_key());
    println!("[→] POST /api/recipe/generate food='{}'", food);
    { let conn = db.lock().unwrap(); let _ = conn.execute("DELETE FROM recipes WHERE food=?1", params![&food]); }
    match generate_and_store(&db, &food).await {
        Ok((title, _)) => Json(serde_json::json!({"ok": true, "title": title, "food": food})).into_response(),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(serde_json::json!({"error": e}))).into_response(),
    }
}

// ─── Recipe management endpoints (web UI) ─────────────────────────────────────

#[derive(Serialize)]
struct RecipeListItem {
    food:     String,
    category: String,
    title:    Option<String>,
    cached:   bool,
}

// GET /api/recipes — all foods with recipe cache status
async fn list_recipes(State(db): State<Db>) -> impl IntoResponse {
    let conn = db.lock().unwrap();
    let tables = [("breakfast","breakfast"),("curries","curries"),
                  ("snacks","snacks"),("desserts","desserts")];
    let mut items: Vec<RecipeListItem> = Vec::new();
    for (tbl, cat) in &tables {
        let sql = format!(
            "SELECT f.name, r.title FROM {tbl} f LEFT JOIN recipes r ON r.food = f.name ORDER BY f.id"
        );
        if let Ok(mut stmt) = conn.prepare(&sql) {
            let rows: Vec<RecipeListItem> = stmt
                .query_map([], |row| {
                    let title: Option<String> = row.get(1)?;
                    Ok(RecipeListItem {
                        food:     row.get(0)?,
                        category: cat.to_string(),
                        cached:   title.is_some(),
                        title,
                    })
                })
                .unwrap()
                .filter_map(|r| r.ok())
                .collect();
            items.extend(rows);
        }
    }
    Json(items)
}

fn parse_packed_body(body: &str) -> (Vec<String>, Vec<String>) {
    let mut ingredients = Vec::new();
    let mut steps = Vec::new();
    let mut section = "";
    for line in body.lines() {
        let t = line.trim();
        if t == "|" || t == "---END---" { section = ""; continue; }
        if t.eq_ignore_ascii_case("INGREDIENTS") { section = "i"; continue; }
        if t.eq_ignore_ascii_case("STEPS")       { section = "s"; continue; }
        if t.is_empty() { continue; }
        match section {
            "i" => ingredients.push(t.to_string()),
            "s" => steps.push(t.to_string()),
            _   => {}
        }
    }
    (ingredients, steps)
}

// GET /api/recipe/detail?food=X — parsed recipe as JSON
async fn recipe_detail(
    State(db): State<Db>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let food = params.get("food").cloned().unwrap_or_default();
    let conn = db.lock().unwrap();
    match conn.query_row(
        "SELECT title, body FROM recipes WHERE food=?1",
        params![&food],
        |r| Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?)),
    ) {
        Ok((title, body)) => {
            let (ingredients, steps) = parse_packed_body(&body);
            Json(serde_json::json!({
                "food": food, "title": title,
                "ingredients": ingredients, "steps": steps
            })).into_response()
        }
        Err(_) => (StatusCode::NOT_FOUND,
                   Json(serde_json::json!({"error":"no recipe cached"}))).into_response(),
    }
}

#[derive(Deserialize)]
struct RecipeDetailInput { title: String, ingredients: Vec<String>, steps: Vec<String> }

// PUT /api/recipe/detail?food=X — save edited recipe
async fn recipe_detail_update(
    State(db): State<Db>,
    Query(params): Query<HashMap<String, String>>,
    Json(input): Json<RecipeDetailInput>,
) -> impl IntoResponse {
    let food = params.get("food").cloned().unwrap_or_default();
    let mut body = String::from("INGREDIENTS\n");
    for i in &input.ingredients { body.push_str(i); body.push('\n'); }
    body.push_str("|\nSTEPS\n");
    for s in &input.steps { body.push_str(s); body.push('\n'); }
    body.push_str("|\n");
    let conn = db.lock().unwrap();
    match conn.execute(
        "INSERT INTO recipes (food,title,body) VALUES(?1,?2,?3) \
         ON CONFLICT(food) DO UPDATE SET title=?2, body=?3",
        params![&food, &input.title, &body],
    ) {
        Ok(_)  => Json(serde_json::json!({"ok":true})).into_response(),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR,
                   Json(serde_json::json!({"error":e.to_string()}))).into_response(),
    }
}

// DELETE /api/recipe/detail?food=X — delete cached recipe
async fn recipe_detail_delete(
    State(db): State<Db>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let food = params.get("food").cloned().unwrap_or_default();
    let conn = db.lock().unwrap();
    let _ = conn.execute("DELETE FROM recipes WHERE food=?1", params![&food]);
    Json(serde_json::json!({"ok":true}))
}

// setup_db — idempotent schema init + migrations.
// Migrations handled inline:
//   - recipes table: if old schema has date_key column, drop and recreate with UNIQUE(food).
//   - food tables: add ingredient column if missing (ALTER TABLE ... ADD COLUMN is a no-op on error).
fn setup_db(conn: &Connection) {
    conn.execute_batch("
        CREATE TABLE IF NOT EXISTS breakfast  (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, notes TEXT);
        CREATE TABLE IF NOT EXISTS curries    (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, notes TEXT);
        CREATE TABLE IF NOT EXISTS snacks     (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, notes TEXT);
        CREATE TABLE IF NOT EXISTS desserts   (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, notes TEXT);
        CREATE TABLE IF NOT EXISTS condiments   (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS ingredients  (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);
        CREATE TABLE IF NOT EXISTS recipes (
            id    INTEGER PRIMARY KEY AUTOINCREMENT,
            food  TEXT NOT NULL UNIQUE,
            title TEXT NOT NULL,
            body  TEXT NOT NULL
        );
    ").expect("DB schema init failed");

    // Migrate: recreate recipes if old schema still has date_key column
    if conn.prepare("SELECT date_key FROM recipes LIMIT 1").is_ok() {
        let _ = conn.execute_batch("
            DROP TABLE recipes;
            CREATE TABLE recipes (
                id    INTEGER PRIMARY KEY AUTOINCREMENT,
                food  TEXT NOT NULL UNIQUE,
                title TEXT NOT NULL,
                body  TEXT NOT NULL
            );
        ");
        println!("[db] recipes table migrated to food-keyed schema");
    }

    // Migrate: add ingredient column if not already present
    for tbl in &["breakfast", "curries", "snacks", "desserts"] {
        let sql = format!("ALTER TABLE {} ADD COLUMN ingredient TEXT", tbl);
        let _ = conn.execute_batch(&sql); // ignore error if column already exists
    }
}

#[tokio::main]
async fn main() {
    let db_path    = std::env::var("FOOD_DB_PATH").unwrap_or_else(|_| "data/food.db".to_string());
    let static_dir = std::env::var("FOOD_STATIC_DIR").unwrap_or_else(|_| "static".to_string());

    let conn = Connection::open(&db_path).expect("Cannot open data/food.db");
    setup_db(&conn);
    let db: Db = Arc::new(Mutex::new(conn));
    let in_progress: InProgress = Arc::new(Mutex::new(HashSet::new()));

    let app = Router::new()
        .route("/health",                  get(|| async { "OK" }))
        .route("/api/foods/:category",     get(list_foods).post(add_food))
        .route("/api/foods/:category/:id", put(update_food).delete(delete_food))
        .route("/api/condiments",          get(list_condiments).post(add_condiment))
        .route("/api/condiments/:id",      delete(delete_condiment))
        .route("/api/ingredients",          get(list_ingredients).post(add_ingredient))
        .route("/api/ingredients/:id",     delete(delete_ingredient))
        .route("/api/menu/packed",         get(menu_packed))
        .route("/api/browse/packed",       get(browse_packed))
        .route("/api/recipes",             get(list_recipes))
        .route("/api/recipe/detail",       get(recipe_detail).put(recipe_detail_update).delete(recipe_detail_delete))
        .route("/api/recipe/prefetch",     get(recipe_prefetch))
        .route("/api/recipe/packed",       get(recipe_packed))
        .route("/api/recipe/generate",     post(recipe_generate))
        .fallback_service(ServeDir::new(&static_dir))
        .layer(Extension(in_progress.clone()))
        .with_state(db.clone());

    // Pre-generate recipes for all uncached foods at startup.
    // Sequential (not parallel) so Ollama isn't overwhelmed with concurrent requests.
    // Uses INSERT OR IGNORE — existing recipes are never overwritten.
    // Once the full food list is cached this task completes in milliseconds.
    tokio::spawn(async move {
        let tables = ["breakfast", "curries", "snacks", "desserts"];
        let all_foods: Vec<String> = {
            let conn = db.lock().unwrap();
            let mut foods = Vec::new();
            for tbl in &tables {
                let sql = format!("SELECT name FROM {} ORDER BY id", tbl);
                if let Ok(mut stmt) = conn.prepare(&sql) {
                    let names: Vec<String> = stmt
                        .query_map([], |r| r.get(0)).unwrap()
                        .filter_map(|r| r.ok()).collect();
                    for name in names {
                        if !foods.contains(&name) { foods.push(name); }
                    }
                }
            }
            foods
        };

        let mut pending = 0;
        for food in &all_foods {
            let cached = {
                let conn = db.lock().unwrap();
                conn.query_row("SELECT id FROM recipes WHERE food=?1", params![food], |_| Ok(())).is_ok()
            };
            if !cached {
                pending += 1;
                in_progress.lock().unwrap().insert(food.clone());
                match generate_and_store(&db, food).await {
                    Ok((title, _)) => println!("[✓] pre-gen: {}", title),
                    Err(e)         => eprintln!("[!] pre-gen failed '{}': {}", food, e),
                }
                in_progress.lock().unwrap().remove(food);
            }
        }
        if pending == 0 {
            println!("[✓] all {} foods already cached", all_foods.len());
        } else {
            println!("[✓] pre-gen complete: {} new recipes", pending);
        }
    });

    let listener = tokio::net::TcpListener::bind("0.0.0.0:9091").await.unwrap();
    println!("Food Manager → http://localhost:9091");
    axum::serve(listener, app).await.unwrap();
}
